apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-manager
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-manager-role
rules:
  - apiGroups: ["infra.contrib.fluxcd.io"]
    resources: ["terraforms"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["infra.contrib.fluxcd.io"]
    resources: ["terraforms/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["source.toolkit.fluxcd.io"]
    resources: ["gitrepositories"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-manager-binding
subjects:
  - kind: ServiceAccount
    name: terraform-manager
    namespace: flux-system
roleRef:
  kind: ClusterRole
  name: terraform-manager-role
  apiGroup: rbac.authorization.k8s.io
