apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: ippool-prod
spec:
  cidrs:
  - cidr: "192.168.11.240/29"
---
apiVersion: "cilium.io/v2" 
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux 
  interfaces:
  - eth0
  loadBalancerIPs: true
  externalIPs: true