apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: "1.18.6"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    k8sServiceHost: "192.168.11.47"
    k8sServicePort: 6443
    kubeProxyReplacement: "true"
    
    l2announcements:
      enabled: true
    
    k8sClientRateLimit:
      qps: 50
      burst: 100

    devices: "eth0"

    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]

    ingressController:
      enabled: true
      default: true
      loadbalancerMode: shared

    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true