apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  # Flux가 CRD를 직접 관리하도록 정책 추가
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: cilium
      version: "1.18.6"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    k8sServiceHost: "192.168.11.50"
    k8sServicePort: 6443
    kubeProxyReplacement: "true"
    
    k8s:
      requireIPv4PodCIDR: true

    k8sClientRateLimit:
      qps: 50
      burst: 100

    bpf:
      extraArgs:
        - "-Wno-macro-redefined"

    devices: ""
    installIptablesRules: true

    ipam:
      mode: "cluster-pool"
      operator:
        clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]

    ingressController:
      enabled: true
      default: true
      loadbalancerMode: shared
      service:
        type: NodePort
        nodePorts:
          http: 30080
          https: 30443
      proxyProtocol: false
    envoy:
      enabled: true
      
    installCRDs: true

    operator:
      replicas: 1

    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true