apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "1.14.5"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    kubeProxyReplacement: "true"
    k8sServiceHost: "192.168.11.46"
    k8sServicePort: 6443

    k8sClientRateLimit:
      qps: 50
      burst: 100

    nodePort:
      enabled: true

    l2announcements:
      enabled: false

    externalIPs:
      enabled: true

    ingressController:
      enabled: true
      default: true
      # loadbalancerMode: dedicated
      # secretsBackend: local
      # replicas: 1
      loadbalancerMode: shared
      service:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ip-pool: "ippool-prod"

    hubble:
      enabled: true
      
      relay:
        enabled: true
      
      ui:
        enabled: true
        ingress:
          enabled: true
          className: "cilium"
          annotations:
            cert-manager.io/cluster-issuer: "selfsigned-issuer"
          hosts:
            - hubble.avgmax.team
          tls:
            - secretName: hubble-ui-tls
              hosts:
                - hubble.avgmax.team