apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: semaphore
  namespace: semaphore
spec:
  interval: 30m
  chart:
    spec:
      chart: semaphore
      version: "16.0.11"
      sourceRef:
        kind: HelmRepository
        name: semaphoreui
        namespace: flux-system
  values:
    config:
      generate: true
      # cookie_secret: "U29tZVJhbmRvbVN0cmluZ0ZvckNvb2tpZVNlY3JldA=="
      
    admin:
      username: "admin"
      password: "password123"
      name: "Admin User"
      email: "admin@localhost"

    postgresql:
      enabled: true
      auth:
        postgresPassword: "db-password"
        username: semaphore
        password: "db-password"
        database: semaphore

    database:
      type: postgres
      host: postgresql
      port: 5432
      usernameFromSecret: false
      passwordKey: password
      existingSecret: postgresql

    service:
      type: ClusterIP
      port: 3000
      targetPort: 3000

    ingress:
      enabled: false