apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: semaphore
  namespace: semaphore
spec:
  interval: 30m
  chart:
    spec:
      chart: semaphore
      version: "16.0.11"
      sourceRef:
        kind: HelmRepository
        name: semaphore
        namespace: flux-system
  values:
    admin:
      username: "admin"
      password: "password123"
      name: "Admin User"
      email: "admin@localhost"

    postgresql:
      enabled: true
      auth:
        postgresPassword: "db-password"
        username: semaphore
        password: "db-password"
        database: semaphore

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: true
      className: "cilium"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: semaphore.avgmax.team
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: semaphore-tls
          hosts:
            - semaphore.avgmax.team