apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: semaphore
  namespace: semaphore
spec:
  interval: 30m
  chart:
    spec:
      chart: semaphore
      version: "16.0.11"
      sourceRef:
        kind: HelmRepository
        name: semaphore
        namespace: flux-system
  values:
    admin:
      username: "admin"
      password: "password123"
      name: "Admin User"
      email: "admin@localhost"

    postgresql:
      enabled: true
      auth:
        postgresPassword: "db-password"
        username: semaphore
        password: "db-password"
        database: semaphore

    service:
      type: ClusterIP
      port: 3000
      targetPort: 3000

    ingress:
      enabled: false
      # className: "cilium"
      # annotations:
      #   cert-manager.io/cluster-issuer: "selfsigned-issuer"
      #   ingress.cilium.io/backend-protocol: "http"
      #   ingress.cilium.io/force-https: "true"
      # hosts:
      #   - host: semaphore.avgmax.team
      #     paths:
      #       - path: /
      #         pathType: Prefix
      #         backend:
      #           service:
      #             name: semaphore
      #             port:
      #               number: 3000
      # tls:
      #   - secretName: semaphore-tls
      #     hosts:
      #       - semaphore.avgmax.team