apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lago
  namespace: lago
spec:
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  chart:
    spec:
      chart: lago
      version: "1.27.1"
      sourceRef:
        kind: HelmRepository
        name: lago
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: flux-system
    - name: lago-postgresql
      namespace: lago
    - name: lago-redis
      namespace: lago
  valuesFrom:
    - kind: Secret
      name: lago-chart-values
      valuesKey: values.yaml

  values:
    apiUrl: "https://lago-api.avgmax.team"
    frontUrl: "https://lago.avgmax.team"

    front:
      service:
        type: ClusterIP
        port: 80
      ingress:
        enabled: false
      resources:
        requests:
          cpu: 50m
          memory: 64Mi

    api:
      service:
        type: ClusterIP
        port: 3000
      ingress:
        enabled: false
      resources:
        requests:
          cpu: 100m
          memory: 256Mi

    worker:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi

    clockWorker:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi

    billingWorker:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi

    paymentWorker:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi

    webhookWorker:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi

    eventsWorker:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi

    pdfWorker:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi

    pdf:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi

    postgresql:
      enabled: false

    redis:
      enabled: false
