apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zitadel-ingress
  namespace: zitadel
  annotations:
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
    # ingress.cilium.io/backend-protocol: "http"
spec:
  ingressClassName: cilium
  tls:
    - hosts:
        - zitadel.avgmax.team
      secretName: zitadel-tls
  rules:
    - host: zitadel.avgmax.team
      http:
        paths:
          - path: /ui/v2/login
            pathType: Prefix
            backend:
              service:
                name: zitadel-login
                port:
                  number: 3000
          # Since not all of zitadel's grpc endpoints are under /v2, we expose zitadel via NodePort and use HTTP for the ingress.
          # cf. https://sofianedjerbi.com/en/blog/argocd-cli-cilium-gateway-grpc/
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: zitadel
          #       port:
          #         number: 8080