apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: zitadel
spec:
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: zitadel
      version: "9.26.0" # 최신 버전 확인 필요
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: zitadel-secrets
      valuesKey: values.yaml

  values:
    zitadel:
      configmapConfig:
        ExternalDomain: zitadel.avgmax.team
        ExternalPort: 443
        ExternalSecure: true
        TLS:
          Enabled: false
    postgresql:
      enabled: true
      auth:
        username: zitadel
        database: zitadel