apiVersion: ENC[AES256_GCM,data:wUw=,iv:tc60baY8iKBcvd+gXAPYoObnnUunAVLU1NCdYP7y4VM=,tag:JuQ9HSz3yOingSP3GqwZgg==,type:str]
kind: ENC[AES256_GCM,data:dkKaR+LK,iv:ZM7ydHnVg3L0ixeTqHUUvLgHomtv3OuqNav5poT/wtE=,tag:5LLsE+Wk+J5KBI1kpbLLsA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:fK0liVsOpyrP+c+qZSbU,iv:Oic814BXbO8rXwIwVNPJbTDC1y/f8sZAVH/nW5W3wEo=,tag:euYKjJeuRkzlYfxbGBUoWw==,type:str]
    namespace: ENC[AES256_GCM,data:57RC6uwEbg==,iv:aTcVQNi9uEjQ3pIRlXqnqpTIC+pKlvZTpLqfcVvJPIM=,tag:aboh9sZDheB3VEs8K4R0EQ==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:C9/0iBWjwRnQwvQXl4myC34O/n5Gn0g2XRfHTQCQv3WpVO/yk6u6Ehau5rnzgrGeC5WI2krOcBfjqtv/YDzVMUtE53u1ZFGmTVt4eEnk44qAM4BXmRcP11C5NOTtn6HREmmD1/sPdUYdRqqS9jl26brOYUTscZVarPhjqkfaXkTzM1uvxAe0voTs+13HOQqUAmGKF8yB3ePJgN1GvM6DQaQzEBIwmZGTjzKOVmSqZAbczr9aVG3C8anq+flWCwjBHcmZMZ8ePPyn7alKzoVIW+Y9lIMdDM1aa7tivuha1BLH/eEXVNqOTG3kDpZ5ir+x/xmeQQCPER+3T9Q7yLWGP49DCXMF/twjxqw25gsUFiVEOQvy8WxkUX17Bly1CVT9Epyb2wCljCU0WuUQSARv9qlzJzVyQAci2uXkh0nEGSOSOBxRFHrsfQixXEK+ZHshOi0c5DMEqi2MlenxxQGTizSFwZj4xesjAw5VmvfgZ+U=,iv:NlM5ff3uxoGTuJ7QmYdhvogo76lZQzeiB2mMLEIHJ4M=,tag:hEc25nEiC83fHvMqWNQHTw==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvK0lrZ1ZsTXNnY2lMa2sv
            NFBxK1BoUmlIQnlFWjNTSDVxNEtpZUU1TDNJCmQvbU9QTFBmMTJFN0dxV1FTc0lj
            cmdtUVNURU9YT2lnN0hLWUd6NzhoVk0KLS0tIFBhNXZTZ3hsbnQ4UVRwOUpmdmsz
            Z2lUUlVoS1NSNzFwODNLNFdBZ2JSc28KW19c7+78f1zd2FK3EnCKAF7pl2cXM9Ak
            S+GVKob6/53F2z+knLCcasZOo1MksEynxxY/sISSAyXRl4C+sEaHLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-15T08:56:10Z"
    mac: ENC[AES256_GCM,data:Xx1xy5U+Vja2GYmqPMIQ/WLmqBUGWJ/ebJs2aAhFraL1h7irDfUOKK9bs8OfvK8ajWnRK7TA7aHQrndwsFh40Hwt5bxl9rihFAVLb56Og/i3anYl9VuUsuwueco8t6hsD7lGt08bHwuw/auIGZIeH07/m2NnweIRR2l2htMPd9w=,iv:BiFz41X7s9TWe+zZja/oRmUY3SZXVQaZOH/Zned53vE=,tag:mdsqVMFPDNfJrngZUKjTmw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
