apiVersion: ENC[AES256_GCM,data:WUY=,iv:vzqles/UpBVFElvfFIEr5AKYKgMQLQNFp5wE+fqlRo8=,tag:/6o+ORyzeK5XjWnz9xxjSQ==,type:str]
kind: ENC[AES256_GCM,data:q6jwt+gJ,iv:3JCLABTBKQ41cFN0OjYmkSmzW4WYBbFymU9WnbdRev8=,tag:gdY35yaOsf0IIvr0kgRsVA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:SjarjuiHiIPrtFkTdKvZ,iv:BFl702zCFwtU6uxqVfCMmrb+4MQe/1QGkA7zo2+d8sc=,tag:0nCbCgCXqn9C2RyCbkpL7w==,type:str]
    namespace: ENC[AES256_GCM,data:fqPa9ApY+w==,iv:WZaPJTw1OVIVEcFLDlV8KuFJre39b0paqvKIQg2OUbM=,tag:XmZF4wZ8EkNAxnoHrlyU+A==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:De1Wc0X9Mktx7AuXD4Uw8HIIEWX5DGXhdC4A5xF/B81TvI4HtqpCHawLGxWT3GZhjIMJfjCtmGPsvc5cpmsr0/u1gWAJThT434t3cpWODfcjgBuXOE8rT9RuO5u36Yv1rb7V3SmnrxW6cfukMa++lEchnJpSKFfl7M3TbLm+55l8HpPCUp6E5bOjpMAXA/PnUe7Nxeu50m7kcXS5Ee5y5FxY2E4C3jdi9JDU2Mhc2M1il8oqJb8BxWgRYnHvKucOuj0LGuO2hs9hhXvLC3Rj69/5+ZCrS5LAMZOurzJGqW+F4JEgTZWFZDymZRuj6RhoVBCbN8XzC8hkDQTGDWTJaeScbpJNzWFSFRAaC/TRLZ09Ue45EZZWm6hr0oEakyE/CJWuAs/oQJXmqhocy9J51pW+KnBZyk/WR3W3nw9rfim1Z0Q6PpeRxsyZTnfK+Pvf4zHQtg4v/V2R3YyUgOov4FMfhiLx95qfgja/8ixC7dPImzzcALeupDPI/Q==,iv:XCW16IiEtkT1bFrxgFFmnb7ppOASdzRs7y8HVoMwr+g=,tag:q2PXOnFOWqchmC1o5phD3w==,type:str]
    postgresql-values.yaml: ENC[AES256_GCM,data:LUakz3kU/E4HyXUDV0a9NssPiOgwPIK0eyrSsEn+SdCZPgUWMe3abu5GlaaE6QtdywVmRZNxKkwCOwjg+M43n781IFKLGGB8/OYCjBs0eMMPQqDuL51Jkr8FjTXPWeIStcf7vsyL2TJyENpunrh1QXMMhPldXdcUCnLMCaWyujgdfPK5guQp8cz6FqiIRpCWGh0SIg==,iv:yLqWfh9wQrlH3jDUZv1k73o03fipao4mmlvW8gkkl+k=,tag:Eam/m9B2CGpCqQUvTJCjxg==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WHNXTUdPVml3eTNBTnU5
            SDZhWnVYOS93WWczbDF4UWFuR3FiczBtd3lvCnJQNlVablhiaEZmbHN3K0RmOG15
            VjBjTERTVWJhT1lIZkp6eGpiRFFWdjgKLS0tIGZaU2V3VlB3WGg3RXdSSzVMWExv
            TkxlM0djanQwR0t1WTdXbEJ2ZWNhNWcKp/cnLxz8UuuhK0r8/eh6nFsr7qjx67HK
            DnjrLH+dr5xOg5X+bmAmcFkiev1UJWYoutnCcTE9H+51x8Vx2TwRMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T12:51:38Z"
    mac: ENC[AES256_GCM,data:pfSs3qZxC76pIgqsPvMawTE55y2Ivgsk4lEuuY6KoGwRPhv1ji+MWGpRJ7B33ddF8soHYNIkkn/y5CKTc6NVTMbfKJH0jfPbw5ePfKO2a/L7T5haDLSB9A3Ef6nZuy9SVnMtTBfrnCNWxOJuRXm8gzJGpA+8SUQLmWg3Zc/D9SM=,iv:eImaIL9j0zE6/fj+zue/XQeJVKzmAGEFgPZ95NqcIdM=,tag:hUIxmyASCnQDt1F0ShK6TQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
