apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tofu-controller
  namespace: flux-system
spec:
  releaseName: tofu-controller
  interval: 30m
  chart:
    spec:
      chart: tf-controller
      version: "0.15.1"
      sourceRef:
        kind: HelmRepository
        name: tofu-controller
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    reconciler:
      image:
        repository: ghcr.io/flux-iac/tf-runner
        tag: latest