apiVersion: ENC[AES256_GCM,data:Yw8=,iv:QEIfu3U/KHXRQZmn27O2Yk79cL7+YvQlJUgpVK2wYMg=,tag:9qro1dWPqUBZdhOtWZx3Aw==,type:str]
kind: ENC[AES256_GCM,data:bqBXGfr4,iv:grX1jy+COo4nK+V1BABWNIi7UZRIWl3DKErnYmNFmI8=,tag:EpQBrR+ac/jOsHlHZ1L/dQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:u6Xlv6y5kQHIJW7bGY6IjDU=,iv:mA/8GNI4chf5v2S9O8jSrwd/D+xcPgAnADqxwuAu7rQ=,tag:V/B2gKYwNzejUIPiT3xNNw==,type:str]
    namespace: ENC[AES256_GCM,data:ZLMSxLGDh52Tzlo=,iv:NMG9nskesILPCmgLRE4falD9XLXDbIAEzm87gNXQVaQ=,tag:MH+FRU3w+eXiBi5oKndy6Q==,type:str]
type: ENC[AES256_GCM,data:w2XCteb6,iv:aFg94NslC0XK+bGJn4lMZE2X6bumc1V6rVZFMu8pEy8=,tag:uu9W0QJQGGUz7eGS2uD5kg==,type:str]
stringData:
    proxmox_api_url: ENC[AES256_GCM,data:DE9kXwh0OTOIc6jjFW7v/4W1Ui6z261jKn9qRl8iZsCKCw==,iv:F5jN11L3menJLx19Uv5nfnO8LhA1UwC7qYLp+sDcygY=,tag:Q4BabSqTtjf7T7wDqtD4Kw==,type:str]
    proxmox_api_token_id: ENC[AES256_GCM,data:JwluXXJleHn/s6EY+HVQfEc+,iv:mkBjB5yuaP4OqQX7NBvLe+2zUQAkADN3LGaopVKr/sM=,tag:jE9eGfQjWBUeeeOnyRxtng==,type:str]
    proxmox_api_token_secret: ENC[AES256_GCM,data:twWc46Wjwt3+qhf2xZWL2TYRz2IQ1dWlSB9SUM0crCDmNjYC,iv:hjOtGgVFgtQH8Eq0bKYm1sLyH3NeO31RIDXFsXfuUmM=,tag:NFlll5QSRSwoOMRm1LhFOQ==,type:str]
    pve_host_address: ENC[AES256_GCM,data:TfiSNNIpMD03Y3jI,iv:tdS3esGK17QqsVElIS5XzwIBUAN12dvUK/9k9FLi3XQ=,tag:NLImkUy1cYfu7xhrfzLGJg==,type:str]
    pve_ssh_user: ENC[AES256_GCM,data:fpeEPQ==,iv:b4GFK4fsz38N9c8HMZmncwABb5XK36lD1FN55g5LRWY=,tag:H58eoe3+qGIH+ADO9sOWJw==,type:str]
    pve_ssh_private_key_path: ENC[AES256_GCM,data:1PjdkStkV+GBRC5fGfwTFegcDBSu6Jk3,iv:fHRmOpXilHBGAwgBaYNsy3AATnM4sajFpM6Pjz0qVko=,tag:TRAo5w2WcemkjWcSPrXEqA==,type:str]
    vm_ssh_public_key: ENC[AES256_GCM,data:D5wT1ywNkgjXj72WHLrq5Kwfx7CEUKg7N1sS/a7VLmEWaSorwreOl+DdFRcYUdBfID5PAgvTezSRNBHj3390FyEH5sFoue1bTPoov0DTgLBrIsV8xlZ52MNM+v6legTG,iv:hA6Yb7Mliqg66L/QZXWt+7DInlTh0OdurNmeLNAPmgw=,tag:ybF9GOZ9ajiXrYiTKi2NYw==,type:str]
    vm_password: ENC[AES256_GCM,data:LbUWO6B695Y28GcIlWBPHlH8iEMEoaXbHMhXKBlzPIFMtGr84mI6Y5yMKVvggWB8mE8ihtFZffCHrt4Fi5uixoErYueqcXF7Aa6CPGbCmOfeZDqTRUr72DRnr3IZRDIXnpuSAiH1raW8YQ==,iv:savXsJ/QGV6aaoKytqxjq3f7A+GRiklTg5NWuz5UxcU=,tag:GoTDSX8SnXWEvTVDsAxXfA==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RmFDNWtGNWlWVWVmcDZ3
            bDhSckVDRkx4NGx1NlhjVStTbmQ1L1VJQjNBCnk4Ung3T0dZSFhIQlN3L3lDRjZy
            OTZBeThydkttNjhJVXE5QW1neDMwUWMKLS0tIG9wUzdGRDV0amtrbU1wM3VyYUhL
            WHA4SHlYQmFSZDdiMUJaN0l2U1czTnMKgeTkK8velAsDzTsZP0jbBb2jPczwsY+0
            zrudv0kvBQaKgilbqjLwSjAJWMTk2eopVNx87HHsCNWQPGcj1+xsMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T09:08:39Z"
    mac: ENC[AES256_GCM,data:ZNATXyAMvI2Nixv76cJPWIVTLQ/c/RZVmiQ87UYr95+TVlEuS+bhMw09drcaCZeKJ4b0kNcZfNdqwag1t4+hoMNww6GBckPgPVHOlifbNSXWUDLZVoP6x4XIv9x+cpZseduy9YS6GsZBKX73/88rGftJckkkcVVnFi5GgwqwwmU=,iv:e3H3LBnYUjg/KnfxG35rceyoWyrXRfPyYLsyvwmkjvw=,tag:GsdceuzjirJl13Ra+oNTbQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:Rog=,iv:+56cIMzs5D7683fUtQcD5/JjKC4Yfitejjup3LRlRxU=,tag:5yHrxdnngzf93A/nItnBQA==,type:str]
kind: ENC[AES256_GCM,data:HI2EEWPw,iv:aXBO4j/NjFU/iuaTRta1j7E81dDuTiC0HCC5ppWW6lw=,tag:ZU/PzDPZ48nCbBdSVOHOxQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:poRWdFUjflrJri4=,iv:VJgIFp9iqJE7s2rAukJTloDwwzq1NwtIAWbU9aHqQXo=,tag:JffTgs7DK5cUN0DBGyfd0A==,type:str]
    namespace: ENC[AES256_GCM,data:iHPbdHgW4vzzA2M=,iv:dGJh7yEInQxu9UIdOA/+nTedO8134RPJqVuiXT7+dHQ=,tag:WxR1IWeCJwsauq4A4pdzrg==,type:str]
type: ENC[AES256_GCM,data:mJ+JjxnB,iv:UgWsEa/4em0ONUE85yEpxlGoyyjiFxfEoTQyYMVUNoU=,tag:JPXKmdHkNQO3tnkr5Zm+CQ==,type:str]
stringData:
    id_rsa: ENC[AES256_GCM,data:qMHx8EsZVhC4ZD+Bd7E44QuanLNL9fOYdzS49sLnKS28N7rv2Knjkhow83ULJzYxwaD9P0CYQ7n+COIYvUA7XsD83PErmR9GrFyB4r7VDGAS7QIONxivRyHaLPDCF3x0liP6hrzE4CdUoB7QH2M2A3vDAw0H3YgSWRdTbj1cyDtl6WsotB2iMp2i3KAMiOZyWlIEoyu5fr7NmdeDJGgO6lRtvKiiebDR/+uWgthbonom287p5ITcrvf48M+fx581fl3hvs0g46esUADQWfUseEuDxLe2IgIHCY9ERw1e8lEyGpfzekYWQ0Dh+IEumap2WJG5RLTgJoibJjYOzncFjM2dZfPOW4Vt36VAHT7LejiCIrm6w9chuUzRP/BS4vpAHIKEpYEyb75Md7od7TY11Bgm375AHgVQ999pfDg3p7X0M/RXFxe7uEsMsiuw61XqertujCIPlOpj26UvJYFNOwyC+LCOuHgrnMxQvrkdKRcXtbopvPTfpzAxyPLyOcxDM09u3JddOjPgmn4qZ/nk2IsDd9H4IcT1lPLv,iv:ZEGN0XHmkch7g/I7vIfgDFCq5VSWsLptDN6WrPDR4f0=,tag:R6F8tvHUVsqWa/K0F0E7+w==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RmFDNWtGNWlWVWVmcDZ3
            bDhSckVDRkx4NGx1NlhjVStTbmQ1L1VJQjNBCnk4Ung3T0dZSFhIQlN3L3lDRjZy
            OTZBeThydkttNjhJVXE5QW1neDMwUWMKLS0tIG9wUzdGRDV0amtrbU1wM3VyYUhL
            WHA4SHlYQmFSZDdiMUJaN0l2U1czTnMKgeTkK8velAsDzTsZP0jbBb2jPczwsY+0
            zrudv0kvBQaKgilbqjLwSjAJWMTk2eopVNx87HHsCNWQPGcj1+xsMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-25T09:08:39Z"
    mac: ENC[AES256_GCM,data:ZNATXyAMvI2Nixv76cJPWIVTLQ/c/RZVmiQ87UYr95+TVlEuS+bhMw09drcaCZeKJ4b0kNcZfNdqwag1t4+hoMNww6GBckPgPVHOlifbNSXWUDLZVoP6x4XIv9x+cpZseduy9YS6GsZBKX73/88rGftJckkkcVVnFi5GgwqwwmU=,iv:e3H3LBnYUjg/KnfxG35rceyoWyrXRfPyYLsyvwmkjvw=,tag:GsdceuzjirJl13Ra+oNTbQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
