apiVersion: ENC[AES256_GCM,data:2ts=,iv:QyTgdJg0hHVUBmj8D0egpDLIIM3zGGLRM3ew2+GapGU=,tag:NpeVznBvmBOR9o5n00oCvg==,type:str]
kind: ENC[AES256_GCM,data:cXQSdjWa,iv:gnVqFDar6Tal5icojeXwjkfM4usgXTy8H+hlKrlWfXk=,tag:L2RvPbvxWMTXPlnv14RmNA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kxyazJUCk7y1/xluMgBpu2o=,iv:DhzW4jHE5jpLPleUWME9MfLHLXpm0INP+ANulZuZ7P0=,tag:TChR3q9MidVievuaZ55X/g==,type:str]
    namespace: ENC[AES256_GCM,data:RhVPGSOYyKTg248=,iv:F+Cu2zPDzOpJNIIwxax3mIhAftXg0CFXwnLwVeB8Qi0=,tag:97NW7xlWaTDV8XuKx2CO9A==,type:str]
type: ENC[AES256_GCM,data:bPmqLMud,iv:4+40w8ga48ICPD/6fa/UaRuJVdloO3I8Q2JZk0qA4Sg=,tag:wRitzY0G0D22ifDzz4Qy4A==,type:str]
stringData:
    proxmox_api_url: ENC[AES256_GCM,data:CMJzrhYAzTvMVdg2nJNzODbYrh1RK6VOScwgtepc9Or+hg==,iv:zlq+YOwE+U0gpBKhyCazeCvpW/v6R4XdDcy538/4ies=,tag:xzVrja82NY7qQ0cYgHPqvg==,type:str]
    proxmox_api_token_id: ENC[AES256_GCM,data:kF+W8wHTXfAguNC1b8hTXypA,iv:jmuGOToZrx5Ef+ZGyOn4B0rGixHCIzCTRRBEKHz3fXs=,tag:QVzRcHo+eChDon2yrOspdw==,type:str]
    proxmox_api_token_secret: ENC[AES256_GCM,data:sfr7dmVjTTQKyGBT/ZUzS88i0YUlFDLq1wOJY3pK+GQx0qCu,iv:4G0ulqJWf8SxJ77918q7CRl/42E5gSHAjAeGuMIDXGY=,tag:eKUKqn64mJqGDyjbPrh/oA==,type:str]
    pve_host_address: ENC[AES256_GCM,data:QxDqI9tWK5tCoBpJ,iv:AYLGopHcOIDmmNuoyhW30Xnh/Y9G84cRPAulh1HVtHo=,tag:6DeRazrX+hcyN9O6HTxzJw==,type:str]
    pve_ssh_user: ENC[AES256_GCM,data:WLZDOQ==,iv:Xg2F5w+kEI4ynSM/FSReAUPTXygj0R8u+vkgNfheci0=,tag:alWvT4p3ZEQVCW6J1MR8jg==,type:str]
    pve_ssh_private_key_path: ENC[AES256_GCM,data:Ce/zg8VpIzKfVcrbYSpZcuODtUB04ecF,iv:nW06ha1fbeAOMn+qRjEBRl97vlLPSxK+qGvTB+YCTbs=,tag:AMbEWJnd0YZK1IDArydh6A==,type:str]
    vm_ssh_public_key: ENC[AES256_GCM,data:xbVJVhhiAyArFH1txoEu,iv:StU/Mgk+wuugyzb8JrniQdEwu6rg/2IijY2+CCVEoso=,tag:4or2l+9I90bNJpyE+Jzevw==,type:str]
    ansible_ssh_key_path: ENC[AES256_GCM,data:Kak8tgen74GOxGz2O2XcVdLqkhRCVuWI,iv:BLr5Kotx3R4EkifrxCA52Nf1b3Cf8Vt44Mc+r9XuN+U=,tag:itbcsFnnXju1z25QRSK1eA==,type:str]
    vm_password: ENC[AES256_GCM,data:NW6Fb1g4LZDz/iyQhCol6YoYrE3Lgjev1/iOnOfgZPPd1SeBi7kDbZImapSfNyB05x2UmyEhNtGLLK/JINpQy7Dim1XLz9UnpInm/E3nrVIHJ3525L0WISsbrujSitHe/8zVaAi2UjsiCA==,iv:BS1YzgTCabF54LbNcx6a2WJXzbLqRWbpP+uXOEoFFwc=,tag:wWR5TB2kdIcbpBGubULebw==,type:str]
sops:
    age:
        - recipient: age1zddyp0jmektnluxjd2xsj8mnq87q0hnpxndqrajadjqcq3te2vhs8en2rj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQUJjb28zU0FrTWk1WUdU
            aWRBcGpTdzFkcG53TXh6L1pjMHEzaFpJMFNrCm0vUFVNbnJMUTQyQy9lWWR1SllE
            NDhqaXhoQ1F0UUVxVlhydUV6RlJ6ZzgKLS0tIFAwQjF0NDBNYXlHRGJON2RpbFZR
            ZFh1K2RvdzBKcTFRZkEwUEZrL2tCTHcKTIRva0ucaxMgZ1LLQF/rR3gvUCpFW/bj
            oLgoOepqbiU74D5ZK/Z/8wUS3sjIOPgdt3I20ooXEEThdh/nuy4tjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-22T10:18:06Z"
    mac: ENC[AES256_GCM,data:jGWehJPymx04VNLx0P9eg7/Kz6WX/CQ5KBlB5+oyRYkr4rMxFWML0q1SYjiHr57U0u1TRxhS+OYhUiuF5R/FROo1XgCd7grT1uUu/HW+8qMBHmZUI882psHt33xJQrNL989hKb6y1SC5AGZ5qK4w30LnxyGYCpEjBbT20lQPDYw=,iv:QU9cKyhvrnr13zp8xBx4vaRt3UCKeg5kmP4dpwA8eQ8=,tag:N7TMbvKCeI5MBEBthBywiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
