apiVersion: v1
kind: Service
metadata:
  name: teleport-ssh-nodeport
  namespace: teleport
spec:
  type: NodePort
  selector:
    app.kubernetes.io/instance: teleport-teleport-cluster
    app.kubernetes.io/component: proxy
  ports:
    - port: 3023
      targetPort: 3023
      nodePort: 30023