apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-cluster
  namespace: flux-system
spec:
  targetNamespace: teleport
  interval: 30m
  chart:
    spec:
      chart: teleport-cluster
      version: "18.2.10"
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: flux-system
  values:
    clusterName: "teleport.avgmax.team"
    proxyListenerMode: multiplex
    
    auth:
      teleportConfig:
        teleport:
          storage:
            type: dir
            path: /var/lib/teleport

    proxy:
      service:
        type: ClusterIP
        
    ingress:
      enabled: false
      # spec:
      #   ingressClassName: cilium
      # annotations:
      #   cert-manager.io/cluster-issuer: "letsencrypt-prod"
      #   kubernetes.io/ingress.class: "cilium" 
      #   ingress.cilium.io/backend-protocol: "HTTPS"
      #   ingress.cilium.io/secure-backends: "true" 
      # hosts:
      #   - teleport.avgmax.team
      # tls:
      #   - hosts:
      #       - teleport.avgmax.team
      #     secretName: teleport-tls