apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: teleport-cluster
  namespace: teleport
spec:
  targetNamespace: teleport
  interval: 30m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: teleport-cluster
      version: "18.6.4"
      sourceRef:
        kind: HelmRepository
        name: teleport
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: flux-system
  values:
    fullnameOverride: "teleport-cluster"
    clusterName: "teleport.avgmax.team"
    proxyListenerMode: multiplex

    # tls:
    #   existingSecretName: teleport-tls-all

    tls:
      existingSecretName: ""
      certManager:
        enabled: false # teleport 자체 서명 인증서 사용
        # issuerName: "letsencrypt-prod"
        # issuerKind: "ClusterIssuer"

    auth:
      teleportConfig:
        teleport:
          storage:
            type: dir
            path: /var/lib/teleport

    proxy:
      service:
        type: ClusterIP
        
    ingress:
      enabled: false

    # tests: false